name: Run Tests

on:
  push:

  pull_request:
    types: [opened, reopened]

  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 🛎️
        uses: actions/checkout@v4

      - name: node
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0

      - name: Deps
        run: |
          yarn
          yarn build

      - name: Test Schema TypeScript
        run: |
          cd ./packages/schema-typescript && yarn test

      - name: Test OpenAPI Spec
        run: |
          cd ./packages/schema-sdk && yarn test